INSERT INTO `topology` (
  `topology_id`,
  `topology_name`,
  `topology_parent`,
  `topology_page`,
  `topology_order`,
  `topology_group`,
  `topology_url`,
  `topology_url_opt`,
  `topology_popup`,
  `topology_modules`,
  `topology_show`,
  `topology_style_class`,
  `topology_style_id`,
  `topology_OnClick`)
VALUES (
  NULL,
  'Toolbox',
  '527',
  NULL,
  NULL,
  '36',
  NULL,
  NULL,
  NULL,
  NULL,
  '1',
  NULL,
  NULL,
  NULL
);

INSERT INTO `topology` (
  `topology_id`,
  `topology_name`,
  `topology_parent`,
  `topology_page`,
  `topology_order`,
  `topology_group`,
  `topology_url`,
  `topology_url_opt`,
  `topology_popup`,
  `topology_modules`,
  `topology_show`,
  `topology_style_class`,
  `topology_style_id`,
  `topology_OnClick`)
VALUES (
  NULL , 
  'Toolbox', 
  '5', 
  '527', 
  '10', 
  '36', 
  NULL, 
  NULL , 
  NULL , 
  '1', 
  '1', 
  NULL, 
  NULL, 
  NULL
);

INSERT INTO `topology` (
  `topology_id`,
  `topology_name`,
  `topology_parent`,
  `topology_page`,
  `topology_order`,
  `topology_group`,
  `topology_url`,
  `topology_url_opt`,
  `topology_popup`,
  `topology_modules`,
  `topology_show`,
  `topology_style_class`,
  `topology_style_id`,
  `topology_OnClick`)
VALUES (
  NULL , 
  'Configuration', 
  '527', 
  '52701', 
  '5', 
  '36', 
  './modules/centreon-community-toolbox/core/configuration.php', 
  NULL, 
  NULL, 
  '1', 
  '1', 
  NULL, 
  NULL, 
  NULL
);